# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fseires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('tvpartners', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField()),
                ('premiered', models.DateField()),
                ('runtime', models.IntegerField()),
                ('genres', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('image_med', models.URLField()),
                ('image_org', models.URLField()),
                ('imdblink', models.URLField()),
                ('raiting', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='fseires',
            name='seriesname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvseries.Serie'),
        ),
    ]
