# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
