# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvseries', '0002_auto_20170311_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='seria',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
