# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvseries', '0003_serie_seria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='seria',
        ),
        migrations.AddField(
            model_name='serie',
            name='owner',
            field=models.ManyToManyField(related_name='seria', to=settings.AUTH_USER_MODEL),
        ),
    ]
